export interface Product {
    "Czas realizacji"?: string;
    "Grupa klientów 1"?: string;
    "Manager odpowiedzialny"?: string;
    "Paleta": boolean;
    "accessory": boolean;
    "brutto_eur": number;
    "brutto_pln": number;
    "brutto_specialprice_eur": number;
    "brutto_specialprice_pln": number;
    "categories": string[];
    "cids": string[];
    "configurable_options": any | null;
    "created_at": string;
    "createdat": number;
    "description": string;
    "dim_height": string;
    "dim_length": string;
    "dim_width": string;
    "do_wyczerpania_zapasow": boolean;
    "ean": string;
    "entity_id": string;
    "eur_exchange_rate": number;
    "final_price_netto_pln": number;
    "has_options": string;
    "has_special_price": boolean;
    "hide_price": boolean;
    "id": string;
    "ilosc_bokow_przeszkolnych"?: string;
    "image": string;
    "image_medium": string;
    "image_small": string;
    "imgs": any[];
    "is_configurable": boolean;
    "is_new": boolean;
    "is_salable": string;
    "manufacturer": string;
    "meta_description": string;
    "meta_keyword": string;
    "meta_keywords": string;
    "meta_title": string;
    "name": string;
    "name_normalized": string;
    "netto_eur": number;
    "netto_pln": number;
    "netto_specialprice_eur": number;
    "netto_specialprice_pln": number;
    "new_product": boolean;
    "pid": number;
    "popular_product": boolean;
    "price": number;
    "promo": boolean;
    "promo_badge": boolean;
    "qty_sell": string;
    "related_products": any[];
    "required_options": string;
    "sku": string;
    "slug": string;
    "small_image": string;
    "status": boolean;
    "swatch_image": string;
    "thumbnail": string;
    "type_id": string;
    "updated_at": string;
    "url": string;
    "url_key": string;
    "v": string;
    "video": string;
    "visibility": string;
    "weight": string;
    "wyklucz_z_nowosci": boolean;
}

// Typ dla kolekcji produktów (tablicy)
export type ProductsCollection = Product[];